### ISSUE TITLE
Joining forces

### ISSUE THREAD

**Issue by retr0h** [nylas/ansible-test#14]
I am the maintainer of the [molecule](http://molecule.readthedocs.io) project.  I see this project is similar to ours.  Would you be interested in joining forces?

John

**Comment by retr0h** [comment]
![sad keanu](http://cookiesbecrumbling.com/img/cookies12.jpg)

**Comment by retr0h** [comment]
Since this project appears to be forgotten, I was hoping I could get the name to ansible-test.  I would upload molecule v2 as the new ansible-test.  Would you be opposed to that?

**Comment by mat128** [comment]
Thanks to this issue, I found out molecule can use Docker as a driver (and does it wonderfully!).

Leaving this here in hope of helping others.

**Comment by gundalow** [comment]
Ansible already has a tool called `ansible-test` https://github.com/ansible/ansible/blob/devel/test/runner/ansible-test so it would be good to avoid that name for a pip package. We've previously seen people get confused by this
