### ISSUE TITLE
python package index (PyPi) migration breaks ansible-test?

### ISSUE THREAD

**Issue by wuy3** [nylas/ansible-test#19]
When running `ansible-test sanity --list-tests` command from [ansible documentation](https://docs.ansible.com/ansible/devel/dev_guide/testing_sanity.html#id12), the docker instance fails to init due to PyPi erroring out because it can't install ansible into the docker instance(?):

```
vagrant@vagrant-acs:~$ sudo ansible-test sanity --list-tests
Sending build context to Docker daemon  6.405MB
Step 1/8 : FROM debian:7.7
 ---> 6d129b37ec3b
Step 2/8 : MAINTAINER Rob McQueen
 ---> Using cache
 ---> 2497f1a1838e
Step 3/8 : RUN apt-get update && apt-get install -y   python-dev   python-virtualenv   sudo
 ---> Using cache
 ---> 73436b884880
Step 4/8 : RUN mkdir /opt/ansible && virtualenv /opt/ansible/venv && /opt/ansible/venv/bin/pip install ansible
 ---> Running in 7c8aa8fbe804
New python executable in /opt/ansible/venv/bin/python
Installing distribute.............................................................................................................................................................................................done.
Installing pip...............done.
Downloading/unpacking ansible
  Cannot fetch index base URL http://pypi.python.org/simple/
  Could not find any downloads that satisfy the requirement ansible
No distributions at all found for ansible
Storing complete log in /root/.pip/pip.log
The command '/bin/sh -c mkdir /opt/ansible && virtualenv /opt/ansible/venv &&   /opt/ansible/venv/bin/pip install ansible' returned a non-zero code: 1
Traceback (most recent call last):
  File "/usr/local/bin/ansible-test", line 69, in <module>
    main(context)
  File "/usr/local/bin/ansible-test", line 45, in main
    '-t', DOCKER_CONTAINER, '.']
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['docker', 'build', '-t', 'testbox', '.']' returned non-zero exit status 1

```

This is likely caused by the recent PyPi migration of trusted host site (see below)

[Stackoverflow link](https://stackoverflow.com/questions/25981703/pip-install-fails-with-connection-error-ssl-certificate-verify-failed-certi) 
> Note: Sometime during April 2018, the Python Package Index was migrated from pypi.python.org to pypi.org. This means "trusted-host" commands using the old domain no longer work.

**Comment by FloThinksPi** [comment]
@wuy3 this is already fixed in the latest version from github. The standard image is now debian:stable and not debian:7.7 as it is in the version you get from pip. Debian stable already has a newer pip which has knowledge about the changed repo url. 

So theroretically this isnt a issue anymore HOWEVER Guys pls update you pip package ansible-test. It is not working anymore !

**Comment by gtirloni** [comment]
Confirmed installing directly from GitHub works. Please update pip package.

**Comment by wuy3** [comment]
Thanks guys, sorry for the delayed close

**Comment by webknjaz** [comment]
@wuy3 the command mentioned in the Ansible documentation is something that is a part of ansible-core and has nothing to do with this specific package having the same name.
